import { StyleSheet } from 'react-native';

import { colors, radius, shadow, spacing } from '@/src/shared/theme';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  tagScroller: {
    maxHeight: 58,
  },
  tagScrollerContent: {
    alignItems: 'center',
    gap: spacing.md,
    minHeight: 58,
    paddingBottom: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xs,
  },
  filterPill: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.xs,
    height: 40,
    justifyContent: 'center',
    minWidth: 82,
    paddingHorizontal: spacing.lg,
  },
  filterPillText: {
    color: colors.textSoft,
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 20,
  },
  content: {
    alignSelf: 'center',
    maxWidth: 430,
    paddingBottom: 120,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.lg,
    width: '100%',
  },
  gridRow: {
    justifyContent: 'space-between',
  },
  noteCard: {
    aspectRatio: 1,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderWidth: 1,
    marginBottom: spacing.md,
    overflow: 'hidden',
    width: '48.5%',
    ...shadow,
  },
  noteCardBody: {
    flex: 1,
    justifyContent: 'space-between',
    padding: spacing.lg,
    width: '100%',
    zIndex: 1,
  },
  noteCardBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: radius.xl,
    borderWidth: 1,
    zIndex: 0,
  },
  noteText: {
    color: colors.text,
    flexShrink: 1,
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
  },
  noteFooter: {
    flexShrink: 0,
    gap: 2,
  },
  noteDate: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  tagBadge: {
    alignSelf: 'flex-start',
    borderRadius: radius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
  },
  tagBadgeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  emptyCard: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    gap: spacing.md,
    justifyContent: 'center',
    minHeight: 220,
    padding: spacing.xl,
    ...shadow,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '600',
  },
  emptyText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    textAlign: 'center',
  },
  fabLayer: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    paddingBottom: 96,
    paddingRight: 24,
    zIndex: 100,
  },
  fab: {
    alignItems: 'center',
    borderRadius: 32,
    height: 64,
    justifyContent: 'center',
    width: 64,
    ...shadow,
  },
  previewOverlay: {
    flex: 1,
  },
  previewBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.28)',
  },
  previewPanel: {
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    borderColor: 'rgba(255, 255, 255, 0.52)',
    borderRadius: radius.xl,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'absolute',
    ...shadow,
  },
  previewGlass: {
    ...StyleSheet.absoluteFillObject,
  },
  previewPanelContent: {
    flex: 1,
    zIndex: 2,
  },
  previewContentFade: {
    flex: 1,
    gap: spacing.md,
    padding: spacing.lg,
  },
  previewHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  previewClose: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.full,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  previewScroll: {
    flex: 1,
  },
  previewText: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 26,
  },
  previewDate: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  sheetContent: {
    gap: spacing.md,
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  noteInput: {
    height: 180,
    maxHeight: 180,
    minHeight: 180,
  },
  sheetLabel: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: '600',
  },
  tagPicker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  pickerPill: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.full,
    borderWidth: 1,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  pickerPillText: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: '600',
  },
  actions: {
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'flex-end',
    marginTop: spacing.md,
  },
  deleteButton: {
    alignItems: 'center',
    borderColor: colors.danger,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.xs,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: spacing.md,
  },
  deleteText: {
    color: colors.danger,
    fontSize: 14,
    fontWeight: '600',
  },
});
